---
abstract: 'A client library for the Linux Infrared Remote Control'
author:
  - 'Mark Grimes E<lt>mgrimes@cpan.orgE<gt>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IO::Select: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lirc-Client
provides:
  Lirc::Client:
    file: lib/Lirc/Client.pm
    version: 2.00
requires:
  Carp: 0
  File::Path::Expand: 0
  IO::Socket: 1.0
  Moo: 1.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lirc-Client
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/Lirc-Client
version: 2.00
