# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lirc-Client
version:      1.23
version_from: lib/Lirc/Client.pm
installdirs:  site
requires:
    Carp:                          0
    Hash::Util:                    0
    IO::Socket:                    1.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
