---
name: Lirc-Client
version: 1.27
author:
  - 'Mark V. Grimes <mgrimes@cpan.org>'
abstract: A client library for the Linux Infrared Remote Control
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Hash::Util: 0
  IO::Socket: 1.0
provides:
  Lirc::Client:
    file: lib/Lirc/Client.pm
    version: 1.27
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
